###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: topgenerator-redis

    webservice:
      image: nginx:alpine
      container_name: topgenerator-webservice
      working_dir: /application
      volumes:
          - ./:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - php-fpm
        - redis            
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: topgenerator-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
